name: transcation_app
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any
  flutter_bloc: ^9.1.0
  flutter_screenutil: ^5.9.3
  cupertino_icons: ^1.0.8
  dartz: ^0.10.1
  get_it: ^8.0.3
  injectable: ^2.5.0
  image_picker: ^1.1.2
  flutter_svg: ^2.0.17
  connectivity_plus: ^6.1.3
  flutter_image_compress: ^2.4.0
  cached_network_image: ^3.4.1
  badges: ^3.1.2
  flutter_secure_storage: ^9.2.4
  animated_text_kit: ^4.2.3
  flutter_animate: ^4.5.2
  dismissible_page: ^1.0.2
  carousel_slider: ^5.0.0
  http: ^1.3.0
  collection: ^1.19.0
  timeago: ^3.7.0
  url_launcher: ^6.3.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.15
  injectable_generator: ^2.7.0
  flutter_native_splash: ^2.4.4
  flutter_launcher_icons: ^0.14.3

  
  flutter_lints: ^5.0.0


flutter:
  generate: true
  
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/
  #   - images/a_dot_ham.jpeg

  fonts:
    - family: CircularSpotify
      fonts:
        - asset: assets/fonts/CircularSpotifyTxT-Bold.ttf
          weight: 700
        - asset: assets/fonts/CircularSpotifyTxT-Med.ttf
          weight: 500
        - asset: assets/fonts/CircularSpotifyTxT-Light.ttf
          weight: 300
        - asset: assets/fonts/CircularSpotifyTxT-Book.ttf
          weight: 400
